//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controller
    {
        public Controller()
        {
            this.Mesurements = new HashSet<Mesurement>();
        }
    
        public string ControllerType { get; set; }
        public int ControllerNumber { get; set; }
        public string IP_adress { get; set; }
        public Nullable<int> TransformerNumber { get; set; }
    
        public virtual ICollection<Mesurement> Mesurements { get; set; }
    }
}
