//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesurement
    {
        public int ControllerNumber { get; set; }
        public int MesurementNumber { get; set; }
        public System.DateTime MesurementDatetime { get; set; }
        public double OilTemp { get; set; }
        public double AirTemp { get; set; }
        public double PhaseALoading { get; set; }
        public double PhaseBLoading { get; set; }
        public double PhaseCLoading { get; set; }
        public int TransformerNumber { get; set; }
    
        public virtual Controller Controller { get; set; }
        public virtual Transformer Transformer { get; set; }
    }
}
