//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substation
    {
        public Substation()
        {
            this.Transformers = new HashSet<Transformer>();
        }
    
        public string SubstationAdress { get; set; }
        public int SubstationNumber { get; set; }
    
        public virtual ICollection<Transformer> Transformers { get; set; }

        //===========================================
        public override string ToString()
        {
            return SubstationNumber.ToString()+SubstationAdress;
        }
        //===========================================
    }
}
