//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformer
    {
        public Transformer()
        {
            this.Mesurements = new HashSet<Mesurement>();
        }
    
        public double PrimaryVoltage { get; set; }
        public int TransformerNumber { get; set; }
        public string TransformerType { get; set; }
        public double Power { get; set; }
        public double SecondaryVoltage { get; set; }
        public string Produser { get; set; }
        public Nullable<int> YearOfProduction { get; set; }
        public double PscLosses { get; set; }
        public double PoLosses { get; set; }
        public double Vsc { get; set; }
        public double TermalConst { get; set; }
        public Nullable<int> SubstationNumber { get; set; }
    
        public virtual ICollection<Mesurement> Mesurements { get; set; }
        public virtual Substation Substation { get; set; }
    }
}
